apiVersion: v1
kind: PersistentVolume
metadata:
  name: pv-go
spec:
  storageClassName: local-storage
  capacity:
    storage: 2Gi
  accessModes:
    - ReadWriteOnce
  hostPath:
    path: "/pv_go"
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: pvc-go
spec:
  storageClassName: local-storage
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 1Gi
  # volumeMode: Filesystem
---

apiVersion: apps/v1
kind: Deployment
metadata:
  name: go-web-app
spec:
  selector:
    matchLabels:
      app: go-web-app
  template:
    metadata:
      labels:
        app: go-web-app
    spec:
      volumes:
        - name: myvolume
          persistentVolumeClaim:
            claimName: pvc-go

      containers:
      
      - name: application
        image: golang:1.17
        command: ["/bin/sh", "-c"]
        args:
          - echo "deb http://ftp.uk.debian.org/debian jessie-backports main >>/etc/apt/sources.list";
            apt-get -y update;
            apt-get -y install ffmpeg;
            mkdir /pv
            cd /pv && git clone https://github.com/letran3691/echo_gorm.git
            cd /pv && go build -o main .;
            cd /pv && cp youtube-dl /usr/local/bin;
            chmod a+rx /usr/local/bin/youtube-dl;
            /pv/main;


        resources: {}
          # requests:
          #   cpu: "100m"
          #   memory: "100Mi"
          # limits:
          #   cpu: "100m"
          #   memory: "100Mi"

        ports:
        - containerPort: 8000
        volumeMounts:
          - mountPath: /pv
            name: myvolume

---
apiVersion: v1
kind: Service
metadata:
  name: go-web-service
spec:
   type: NodePort
  selector:
    app: go-web-app
  ports:
    - port: 80
      targetPort: 8000
      protocol: TCP
